from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict, Any
import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    symbol: str
    action: str  # "BUY", "SELL"
    quantity: int
    reason: str
    timestamp: pd.Timestamp


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    def __init__(self, config: Dict[str, Any], name: str):
        self.config = config
        self.name = name

    @abstractmethod
    def generate_signals(self, bars: pd.DataFrame) -> list[Signal]:
        """
        Generate trading signals from market data.

        Args:
            bars: DataFrame with OHLCV data (Open, High, Low, Close, Volume)

        Returns:
            List of Signal objects
        """
        pass

    @abstractmethod
    def validate_entry(self, symbol: str, bar: pd.Series) -> bool:
        """
        Validate entry conditions for a specific bar.

        Args:
            symbol: Stock symbol
            bar: Latest bar data (OHLCV)

        Returns:
            True if entry conditions met, False otherwise
        """
        pass

    @abstractmethod
    def validate_exit(self, symbol: str, position: Dict[str, Any], bar: pd.Series) -> Optional[str]:
        """
        Validate exit conditions for an open position.

        Args:
            symbol: Stock symbol
            position: Dict with {entry_price, qty, entry_time}
            bar: Latest bar data (OHLCV)

        Returns:
            Exit reason if should exit ("stop_loss", "take_profit", "timeout"),
            None if should hold
        """
        pass
